### PR TITLE
Insert button style update

### PR DESCRIPTION
**Pull request by jimfrankenstein**
This will work in conjunction with DripEmail/drip#4014

We need an icon to replace the "Insert CTA Button" text, which takes up too much space and sticks out.

screen shot 2017-07-10 at 11 18 49 am

CC @jonpaulhanson

### CODE REVIEW

**Comment by derrickreimer** [comment]
Could be something like `+ CTA` for now.

**Comment by jimfrankenstein** [comment]
Right on.  I'll leave it up to @jonpaulhanson

**Comment by jonpaulhanson** [comment]
Dropped the text and created an icon.  I think it works well.  Also added a shortcodes icon. @djreimer what do you think?

cta-shortcodes-icons

**Comment by derrickreimer** [comment]
Yeah looks nice @jonpaulhanson

**Comment by derrickreimer** [comment]
Assuming there's a tooltip, right?

**Comment by jonpaulhanson** [comment]
Yes, tooltips are there.

**Comment by jonpaulhanson** [comment]
Adding on a fix for DripEmail/drip#5676

screen shot 2017-07-18 at 10 10 49 am

**Review by derrickreimer — APPROVED** [review]
Looking good to me.

Tagging @iantance @jimfrankenstein to assist with getting this merged in.

**Pull request merged**
