### PR TITLE
Create Drip theme for CKEditor

### PR DESCRIPTION
**Pull request by jimfrankenstein**
Created a Drip theme for this editor, ready for review by viewing the sample index page.  There will be some more work to do to factor in for the Drip customizations.

I'm not 100% happy with the icons, so I will be revisiting those.  More work to be done there.

### CODE REVIEW

**Comment by jonpaulhanson** [comment]
@jimfrankenstein Can you take a look at this.  icons are aligned and have some separation, i updated the underline icon, and added some styles for the source view.

**Comment by jimfrankenstein** [comment]
@jonpaulhanson Good catch on the source view!

I liked what you did, though I had to make some edits. There were some spacing issues when the editor was very narrow, and the specific margins were causing some weirdness if the editor was put into right-to-left reading mode, which I was trying to make sure we solved for in this redesign.

**Comment by jimfrankenstein** [comment]
@sbone Your input needed on plugin functionality

**Comment by sbone** [comment]
@jonpaulhanson @jimfrankenstein Got the build working, but things aren't quite right in our app.

To take a look:
1. Inside your CKEditor folder, run:
`./dev/builder/build.sh`
1. Copy the build into the Drip app: 
`cp -R dev/builder/release/ckeditor/ [~/path/to/drip]/public/ckeditor-9999999`
1. Inside the Drip app, checkout branch `ckeditor-dev`
1. Preview in your Editor of choice in Drip

**Comment by jimfrankenstein** [comment]
Pinging @djreimer

**Comment by sbone** [comment]
@jimfrankenstein Mind adding a screenshot or two to the PR description? I know there's one in the original issue, but I think it'd be a nice little reference to see the final result here.

**Comment by jimfrankenstein** [comment]
screen shot 2017-06-27 at 3 31 39 pm

On narrow widths, buttons will wrap to the next line (current functionality)
screen shot 2017-06-27 at 3 31 54 pm

**Review by derrickreimer — APPROVED** [review]
Looks great guys! ❤️ 🎉

**Pull request merged**
