### PR TITLE
skip removing attributes

### PR DESCRIPTION
**Pull request by iantance**
Fixes DripEmail/drip#4586

This solution was suggested in a comment here: http://ckeditor.com/addon/link. It looks like it works to me.

@sbone do you want to take a quick look to see if this looks reasonable?

### CODE REVIEW

**Comment by sbone** [comment]
@iantance Just tested locally and the link `class` has been preserved! 👍 

One small suggestion - I feel like you might as well delete this line and reference the issue in the commit message. What do you think?

**Comment by iantance** [comment]
Removing that line sounds fine to me. Thanks for taking a look!

**Comment by iantance** [comment]
@djreimer Ready for review. I can file a separate PR to update the editor in production.

**Review by derrickreimer — APPROVED** [review]
👍

**Pull request merged**
